### ISSUE TITLE
Как добавить расписание?

### ISSUE THREAD

**Issue by Marat0Sh** [mavrikkk/ha_kettler#8]
Добрый день!
Подскажите пожалуйста как в новой версии сделать автоматическое включение чайника по расписанию? В старой версии, в файле `automations.yaml` было так:

```
 - alias: Kettle_06_30
    trigger:
      platform: time
      at: "06:30:00"
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: water_heater.set_operation_mode
        data:
          entity_id: water_heater.g200s
          operation_mode: electric
```
И всё работало, чайник включался в указанное время. В новой же версии в логах HA возникает ошибка:
`Error executing script. Service not found for call_service at pos 1: Unable to find service kettler/set_operation_mode`

Как я понимаю необходимо верно указать название сервиса и `entity_id`, вот только какие?

**Comment by mavrikkk** [comment]
В HomeAssistant открываете Панель разработчика - службы. и там есть описание всех служб у любого из элементов с подробным описанием что подставить.

Я у себя использую не set_operation_mode а set_temperature

- id: '12345'
  alias: boil kettler
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: water_heater.redmondkettler
      temperature: 100
    service: water_heater.set_temperature

**Comment by Marat0Sh** [comment]
Спасибо, в итоге сделал так:
```
action:
 - service: water_heater.set_operation_mode
 data:
 entity_id: water_heater.redmondkettler
 operation_mode: electric
```
Работает.
